/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include "drivers.h"


void funcOne(void);
void funcTwo(void);

int main(void)
{

	TIM_Init(TIM6);

	// Push Button
	GPIO_Init(GPIOC, 13, INPUT_MODE, OPT_PUSH_PULL, LOW_SPEED, NO_PULL);

	// AUTO GPIO outputs
	GPIO_Init(GPIOC, 0, GPO_MODE, OPT_PUSH_PULL, LOW_SPEED, NO_PULL); // GREEN LED AUTO
	GPIO_Init(GPIOC, 1, GPO_MODE, OPT_PUSH_PULL, LOW_SPEED, NO_PULL); // YELLOW LED AUTO
	GPIO_Init(GPIOB, 0, GPO_MODE, OPT_PUSH_PULL, LOW_SPEED, NO_PULL); // RED LED AUTO

	// PDTR GPIO outputs
	GPIO_Init(GPIOA, 0, GPO_MODE, OPT_PUSH_PULL, LOW_SPEED, NO_PULL); // BLUE LED PDTR
	GPIO_Init(GPIOA, 10, GPO_MODE, OPT_PUSH_PULL, LOW_SPEED, NO_PULL); // RED LED PDTR

	EXTI_init(GPIOC,13,EXTI15_10_IRQn);

	/* Loop forever */
	for(;;){
		if(set){
			// Button debounce logic
			delay(100);
			if(BUTTON_PRESSED){
				set=0;
				funcTwo();
			}
		}
		funcOne();
	}
}

void funcOne(void){
	AUTO_GREEN_LED_ON;
	AUTO_RED_LED_OFF;
	AUTO_YELLOW_LED_OFF;
	PDTR_BLUE_LED_OFF;
	PDTR_RED_LED_ON;
}

void funcTwo(void){
	AUTO_GREEN_LED_OFF;
	AUTO_YELLOW_LED_ON;
	AUTO_RED_LED_OFF;
	PDTR_RED_LED_ON;
	PDTR_BLUE_LED_OFF;
	delay(3000);

	AUTO_GREEN_LED_OFF;
	AUTO_YELLOW_LED_OFF;
	AUTO_RED_LED_ON;
	PDTR_RED_LED_ON;
	PDTR_BLUE_LED_OFF;
	delay(1000);

	AUTO_GREEN_LED_OFF;
	AUTO_YELLOW_LED_OFF;
	AUTO_RED_LED_ON;
	PDTR_RED_LED_OFF;
	PDTR_BLUE_LED_ON;
	delay(10000);

	AUTO_GREEN_LED_OFF;
	AUTO_YELLOW_LED_OFF;
	AUTO_RED_LED_ON;
	PDTR_RED_LED_ON;
	PDTR_BLUE_LED_OFF;
	delay(1000);

	AUTO_GREEN_LED_OFF;
	AUTO_YELLOW_LED_ON;
	AUTO_RED_LED_ON;
	PDTR_RED_LED_ON;
	PDTR_BLUE_LED_OFF;
	delay(2000);
	return;
}

// Interrupt
void EXTI15_10_IRQHandler(void){
	if(EXTI->PR & (BIT_MASK_ONE<<13)){
		set=1;
		EXTI->PR|=(BIT_MASK_ONE<<13);
	}
}
